### ISSUE TITLE
Fmovies, streamtape not working

### ISSUE THREAD

**Issue by jferreira93-web** [mbebe/blomqvist#808]
Hi,

My problem is something strange, for several days the streamtape link gave an error every time I clicked on it, which is annoying because it's what works best it's super stable it works well 95%+ of the time, but I went to check it and on my pc and the streamtape link works and in my android box where it never gave a problem it doesn't work, what could it be? (Videovard works ok, but it's not as stable as streamtape)

It used to work on the two platforms without a problem

**Comment by theface78** [comment]
Basically the problem like Vidstream and MyCloud, these two don't work either with the addon. VideoVard and js working, but seem to be fast with deleting flagged content and FMOVIES doesn't reupload . So in these cases, it's basically unusable. The issue for that is open for almost three weeks now, look below. 

MyCloud and Vidstream seem to change the access keys to their service often, to make add-ons like this here unusable. Probably because they only create traffic, but without any benefit for the hosters. I guess SteamTape did the same now.

**Comment by jferreira93-web** [comment]
> Basically the problem like Vidstream and MyCloud, these two don't work either with the addon. VideoVard and js working, but seem to be fast with deleting flagged content and FMOVIES doesn't reupload . So in these cases, it's basically unusable. The issue for that is open for almost three weeks now, look below.
> 
> MyCloud and Vidstream seem to change the access keys to their service often, to make add-ons like this here unusable. Probably because they only create traffic, but without any benefit for the hosters. I guess SteamTape did the same now.



---


Problem solved!

I just manually updated resolve url and it fixed the problem.

**Comment by theface78** [comment]
How did you do that? Can you upload the fixed file maybe please?

**Comment by jferreira93-web** [comment]
> How did you do that? Can you upload the fixed file maybe please?


I went to the fmovies.to addon dependencies and then I saw that Resolve URL I had was not the last version I clicked and then it update, and now streamtape link works.
